// Catalog data for Espumatex prototype
const ESPUMATEX_CATEGORIES = [
  { slug: 'espumas', name: 'Espumas', count: 84 },
  { slug: 'tecidos', name: 'Tecidos', count: 142 },
  { slug: 'manta-acrilica', name: 'Manta acrílica', count: 12 },
  { slug: 'fibras', name: 'Fibras siliconadas', count: 8 },
  { slug: 'acessorios', name: 'Acessórios', count: 36 },
];

const ESPUMATEX_PRODUCTS = [
  {
    id: 'p1',
    sku: 'ESP-D33-10',
    name: 'Espuma D33 — 10cm',
    slug: 'espuma-d33-10cm',
    category: 'Espumas',
    unit: 'M2',
    basePrice: 89.90,
    density: 'D33',
    thickness: 10,
    width: 1.40,
    badge: 'Mais vendido',
    swatch: 'linear-gradient(135deg, #d9c89a 0%, #b59c6a 100%)',
    short: 'Densidade média-alta. Ideal para assento de sofá e estofamento residencial.',
    rating: 4.8,
    reviews: 312,
  },
  {
    id: 'p2',
    sku: 'ESP-D45-05',
    name: 'Espuma D45 — 5cm',
    slug: 'espuma-d45-5cm',
    category: 'Espumas',
    unit: 'M2',
    basePrice: 64.50,
    density: 'D45',
    thickness: 5,
    width: 1.40,
    badge: null,
    swatch: 'linear-gradient(135deg, #c9b48a 0%, #9d8458 100%)',
    short: 'Alta densidade. Cabeceiras, encostos firmes, restauração.',
    rating: 4.9,
    reviews: 187,
  },
  {
    id: 'p3',
    sku: 'TEC-LIN-AREIA',
    name: 'Linho Belga — Areia',
    slug: 'linho-belga-areia',
    category: 'Tecidos',
    unit: 'M',
    basePrice: 78.00,
    grammage: 280,
    width: 1.50,
    badge: 'Novo',
    swatch: 'linear-gradient(135deg, #e6dcc6 0%, #c9b896 100%)',
    short: 'Linho 100%, gramatura 280g/m². Trama aberta, toque natural.',
    rating: 4.7,
    reviews: 94,
  },
  {
    id: 'p4',
    sku: 'TEC-VEL-GRA',
    name: 'Veludo Premium — Grafite',
    slug: 'veludo-premium-grafite',
    category: 'Tecidos',
    unit: 'M',
    basePrice: 92.00,
    grammage: 340,
    width: 1.40,
    badge: null,
    swatch: 'linear-gradient(135deg, #4a4a52 0%, #2a2a30 100%)',
    short: 'Veludo de poliéster 340g/m². Resistência abrasão 50.000 ciclos.',
    rating: 4.9,
    reviews: 421,
  },
  {
    id: 'p5',
    sku: 'ESP-D20-03',
    name: 'Espuma D20 — 3cm',
    slug: 'espuma-d20-3cm',
    category: 'Espumas',
    unit: 'M2',
    basePrice: 32.40,
    density: 'D20',
    thickness: 3,
    width: 1.40,
    badge: null,
    swatch: 'linear-gradient(135deg, #ddc89e 0%, #b89c6e 100%)',
    short: 'Baixa densidade. Almofadas decorativas, capas, artesanato.',
    rating: 4.6,
    reviews: 256,
  },
  {
    id: 'p6',
    sku: 'TEC-CHE-BOU',
    name: 'Chenille — Bouclé creme',
    slug: 'chenille-boucle-creme',
    category: 'Tecidos',
    unit: 'M',
    basePrice: 58.00,
    grammage: 320,
    width: 1.40,
    badge: 'Promo',
    swatch: 'linear-gradient(135deg, #ede4d0 0%, #d4c5a8 100%)',
    short: 'Tramado bouclé, toque macio, alta resistência.',
    rating: 4.8,
    reviews: 178,
  },
  {
    id: 'p7',
    sku: 'MAN-100',
    name: 'Manta acrílica 100g',
    slug: 'manta-acrilica-100g',
    category: 'Manta acrílica',
    unit: 'M',
    basePrice: 18.50,
    width: 1.50,
    badge: null,
    swatch: 'linear-gradient(135deg, #f4f0e8 0%, #d8d2c2 100%)',
    short: 'Manta de fibra acrílica para almofadas e edredons.',
    rating: 4.7,
    reviews: 142,
  },
  {
    id: 'p8',
    sku: 'ESP-D28-08',
    name: 'Espuma D28 — 8cm',
    slug: 'espuma-d28-8cm',
    category: 'Espumas',
    unit: 'M2',
    basePrice: 71.00,
    density: 'D28',
    thickness: 8,
    width: 1.40,
    badge: null,
    swatch: 'linear-gradient(135deg, #d4c094 0%, #ad9460 100%)',
    short: 'Densidade média. Conforto equilibrado, uso diário.',
    rating: 4.7,
    reviews: 203,
  },
];

window.ESPUMATEX_CATEGORIES = ESPUMATEX_CATEGORIES;
window.ESPUMATEX_PRODUCTS = ESPUMATEX_PRODUCTS;
